import { useMemo, useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Button } from "@/components/ui/button"
import { AskKnowledgeBaseService } from "@/services/ask-knowledge-base/AskKnowledgeBaseService"
import { PandaWikiOpenAIConversationProvider } from "@/services/providers/pandawiki/chat/PandaWikiOpenAIConversationProvider"
import type { PandaWikiChatConfig } from "@/services/providers/pandawiki/chat/PandaWikiChatConfig"

export function PandaWikiAskPanel({ config }: { config: PandaWikiChatConfig }) {
  const [question, setQuestion] = useState("")
  const [answer, setAnswer] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const service = useMemo(
    () => new AskKnowledgeBaseService(new PandaWikiOpenAIConversationProvider(() => config)),
    [config],
  )

  const submit = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!question.trim() || loading) return
    setLoading(true)
    setAnswer(null)
    setError(null)
    const result = await service.ask(question)
    if (result.kind === "answer") setAnswer(result.content)
    else setError(result.message)
    setLoading(false)
  }

  return (
    <aside className="flex w-96 shrink-0 flex-col border-l bg-card">
      <div className="border-b p-4">
        <h2 className="text-sm font-semibold">Ask this knowledge base</h2>
        <p className="mt-1 text-xs text-muted-foreground">Answers are generated by your configured PandaWiki service.</p>
      </div>
      <form className="border-b p-4" onSubmit={submit}>
        <label className="sr-only" htmlFor="pandawiki-question">Question</label>
        <textarea
          id="pandawiki-question"
          className="min-h-28 w-full rounded-lg border bg-background p-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
          placeholder="Ask a question about the authorized knowledge…"
          disabled={loading}
        />
        <Button className="mt-3 w-full" type="submit" disabled={loading || !question.trim() || !config.endpointUrl}>
          {loading ? "Asking PandaWiki…" : "Ask PandaWiki"}
        </Button>
        {!config.endpointUrl && <p className="mt-2 text-xs text-muted-foreground">Configure the chat endpoint and token in the provider settings.</p>}
      </form>
      <div className="min-h-0 flex-1 overflow-auto p-4">
        {error && <p role="alert" className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
        {answer && <div className="prose prose-sm max-w-none dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]}>{answer}</ReactMarkdown></div>}
        {!answer && !error && !loading && <p className="text-sm text-muted-foreground">Ask a question to search the knowledge base.</p>}
      </div>
    </aside>
  )
}
